(function(){
'use strict';var e,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.12.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function k(a){this.Pa=a}k.prototype.toString=function(){return String.fromCharCode(this.Pa)};var ea=function da(a,b,c){var f=new a.ga(b[c]);if(c<b.length-1){a=a.O;c+=1;for(var h=f.c,g=0;g<h.length;g++)h[g]=da(a,b,c)}return f};
function fa(a){switch(typeof a){case "string":return l(ha);case "number":return ia(a)?a<<24>>24===a?l(ja):a<<16>>16===a?l(ka):l(la):ma(a)?l(na):l(oa);case "boolean":return l(pa);case "undefined":return l(qa);default:return null===a?a.yb():a instanceof n?l(ra):a instanceof k?l(sa):a&&a.$classData?l(a.$classData):null}}
function ta(a){switch(typeof a){case "string":return"java.lang.String";case "number":return ia(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":ma(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.yb():a instanceof n?"java.lang.Long":a instanceof k?"java.lang.Character":a&&a.$classData?a.$classData.name:null.D.name}}
function ua(a){switch(typeof a){case "string":return q(a);case "number":return va(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.u():a instanceof n?a.K^a.J:a instanceof k?null===a?0:a.Pa:r.prototype.u.call(a)}}var wa=0,xa=new WeakMap;
function ya(a){switch(typeof a){case "string":return q(a);case "number":return va(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:q(a);default:if(null===a)return 0;b=xa.get(a);void 0===b&&(wa=b=wa+1|0,xa.set(a,b));return b}}function ia(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}
function ma(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function r(){}r.prototype.constructor=r;function t(){}t.prototype=r.prototype;r.prototype.u=function(){return ya(this)};r.prototype.i=function(){var a=this.u();return ta(this)+"@"+(+(a>>>0)).toString(16)};r.prototype.toString=function(){return this.i()};function u(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=null}else this.c=a}u.prototype=new t;u.prototype.constructor=u;function za(){}za.prototype=u.prototype;
function Aa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=!1}else this.c=a}Aa.prototype=new t;Aa.prototype.constructor=Aa;function Ba(a){this.c="number"===typeof a?new Uint16Array(a):a}Ba.prototype=new t;Ba.prototype.constructor=Ba;function Ca(a){this.c="number"===typeof a?new Int8Array(a):a}Ca.prototype=new t;Ca.prototype.constructor=Ca;function Da(a){this.c="number"===typeof a?new Int16Array(a):a}Da.prototype=new t;Da.prototype.constructor=Da;
function Ea(a){this.c="number"===typeof a?new Int32Array(a):a}Ea.prototype=new t;Ea.prototype.constructor=Ea;function Fa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=ba}else this.c=a}Fa.prototype=new t;Fa.prototype.constructor=Fa;function Ga(a){this.c="number"===typeof a?new Float32Array(a):a}Ga.prototype=new t;Ga.prototype.constructor=Ga;function Ha(a){this.c="number"===typeof a?new Float64Array(a):a}Ha.prototype=new t;Ha.prototype.constructor=Ha;
function v(){this.ga=void 0;this.M=this.O=this.p=null;this.N=0;this.sb=null;this.t="";this.v=this.L=this.za=void 0;this.name="";this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c,d){var f=new v;f.p={};f.sb=a;f.t=b;f.v=h=>h===f;f.name=c;f.isPrimitive=!0;f.isInstance=()=>!1;void 0!==d&&(f.L=Ia(f,d));return f}
function x(a,b,c,d){var f=new v,h=ca(a);f.p=c;f.t="L"+b+";";f.v=g=>!!g.p[h];f.name=b;f.isInterface=!1;f.isInstance=d||(g=>!!(g&&g.$classData&&g.$classData.p[h]));return f}function Ia(a,b,c){var d=new v;b.prototype.$classData=d;var f="["+a.t;d.ga=b;d.p={a:1,ia:1,b:1};d.O=a;d.M=a;d.N=1;d.t=f;d.name=f;d.isArrayClass=!0;d.v=c||(h=>d===h);d.isInstance=h=>h instanceof b;return d}
function Ja(a){function b(m){if("number"===typeof m){this.c=Array(m);for(var p=0;p<m;p++)this.c[p]=null}else this.c=m}var c=new v;b.prototype=new za;b.prototype.constructor=b;var d=a.M||a,f=a.N+1;b.prototype.$classData=c;var h="["+a.t;c.ga=b;c.p={a:1,ia:1,b:1};c.O=a;c.M=d;c.N=f;c.t=h;c.name=h;c.isArrayClass=!0;var g=m=>{var p=m.N;return p===f?d.v(m.M):p>f&&d===y};c.v=g;c.isInstance=m=>{m=m&&m.$classData;return!!m&&(m===c||g(m))};return c}function Ka(a){a.L||(a.L=Ja(a));return a.L}
function l(a){a.za||(a.za=new z(a));return a.za}v.prototype.isAssignableFrom=function(a){return this===a||this.v(a)};v.prototype.checkCast=function(){};v.prototype.getSuperclass=function(){return this.Wb?l(this.Wb):null};v.prototype.getComponentType=function(){return this.O?l(this.O):null};v.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ka(b);return ea(b,a,0)};var y=new v;y.p={a:1};y.t="Ljava.lang.Object;";y.v=a=>!a.isPrimitive;y.name="java.lang.Object";
y.isInstance=a=>null!==a;y.L=Ia(y,u,a=>{var b=a.N;return 1===b?!a.M.isPrimitive:1<b});r.prototype.$classData=y;w(void 0,"V","void",void 0);w(!1,"Z","boolean",Aa);w(0,"C","char",Ba);w(0,"B","byte",Ca);w(0,"S","short",Da);w(0,"I","int",Ea);var La=w(null,"J","long",Fa);w(0,"F","float",Ga);w(0,"D","double",Ha);function Ma(){window.document.documentElement}Ma.prototype=new t;Ma.prototype.constructor=Ma;Ma.prototype.$classData=x({tb:0},"dotty.tools.scaladoc.ContentContributors",{tb:1,a:1});
function z(a){this.D=a}z.prototype=new t;z.prototype.constructor=z;z.prototype.i=function(){return(this.D.isInterface?"interface ":this.D.isPrimitive?"":"class ")+this.D.name};z.prototype.$classData=x({Db:0},"java.lang.Class",{Db:1,a:1});function Na(){this.Ua=this.ja=this.P=null;Oa=this;this.P=new ArrayBuffer(8);this.ja=new Int32Array(this.P,0,2);new Float32Array(this.P,0,2);this.Ua=new Float64Array(this.P,0,1);this.ja[0]=16909060;new Int8Array(this.P,0,8)}Na.prototype=new t;
Na.prototype.constructor=Na;function Pa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.Ua[0]=b;return(a.ja[0]|0)^(a.ja[1]|0)}Na.prototype.$classData=x({Gb:0},"java.lang.FloatingPointBits$",{Gb:1,a:1});var Oa;function Qa(){Oa||(Oa=new Na);return Oa}
function Ra(){this.Va=this.Ba=null;Sa=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Ba=a;this.Va=null}Ra.prototype=new t;Ra.prototype.constructor=Ra;function Ta(a,b,c){return null!==a.Ba?(a=a.Ba,Ua||(Ua=new Va),Ua.Xa.call(a,b)?a[b]:c):Ta(a.Va,b,c)}Ra.prototype.$classData=x({Pb:0},"java.lang.System$SystemProperties$",{Pb:1,a:1});var Sa;function Va(){this.Xa=null;Ua=this;this.Xa=Object.prototype.hasOwnProperty}Va.prototype=new t;Va.prototype.constructor=Va;Va.prototype.$classData=x({Rb:0},"java.lang.Utils$Cache$",{Rb:1,a:1});
var Ua,qa=x({Sb:0},"java.lang.Void",{Sb:1,a:1},a=>void 0===a);function Wa(){}Wa.prototype=new t;Wa.prototype.constructor=Wa;Wa.prototype.$classData=x({Tb:0},"java.util.Arrays$",{Tb:1,a:1});var Xa;function n(a,b){this.K=a;this.J=b}n.prototype=new t;n.prototype.constructor=n;n.prototype.u=function(){return this.K^this.J};n.prototype.i=function(){Ya();var a=this.K,b=this.J;return b===a>>31?""+a:0>b?"-"+Za(-a|0,0!==a?~b:-b|0):Za(a,b)};
n.prototype.$classData=x({vb:0},"org.scalajs.linker.runtime.RuntimeLong",{vb:1,a:1});
function Za(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+(Math.clz32(1E9)|0)|0)-(0!==b?Math.clz32(b)|0:32+(Math.clz32(a)|0)|0)|0,d=c,f=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var h=a,g=b;for(a=b=0;0<=c&&0!==(-2097152&g);){var m=h,p=g,B=f,T=d;if(p===T?(-2147483648^m)>=(-2147483648^B):(-2147483648^p)>=(-2147483648^T))m=g,p=d,g=h-f|0,m=(-2147483648^g)>(-2147483648^h)?-1+(m-p|0)|0:m-p|0,h=g,g=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;f=f>>>1|0|d<<31;d=m}c=
g;if(0===c?-1147483648<=(-2147483648^h):-2147483648<=(-2147483648^c))c=4294967296*g+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function $a(){this.da=0}$a.prototype=new t;$a.prototype.constructor=$a;
function ab(a,b){if(-0x7fffffffffffffff>b)return a.da=-2147483648,0;if(0x7fffffffffffffff<=b)return a.da=2147483647,-1;var c=b|0,d=b/4294967296|0;a.da=0>b&&0!==c?-1+d|0:d;return c}$a.prototype.$classData=x({wb:0},"org.scalajs.linker.runtime.RuntimeLong$",{wb:1,a:1});var bb;function Ya(){bb||(bb=new $a);return bb}function cb(a,b,c,d,f){var h=b.o;0!==c.length&&(h.e=""+h.e+c);a=a.k();if(a.h())for(c=a.g(),h.e=""+h.e+c;a.h();)h.e=""+h.e+d,c=a.g(),h.e=""+h.e+c;0!==f.length&&(h.e=""+h.e+f);return b}
function db(){eb=this}db.prototype=new t;db.prototype.constructor=db;db.prototype.$classData=x({kc:0},"scala.collection.StringOps$",{kc:1,a:1});var eb;function fb(){this.ob=null;gb=this;this.ob=new u(0)}fb.prototype=new t;fb.prototype.constructor=fb;fb.prototype.$classData=x({Bc:0},"scala.collection.immutable.VectorStatics$",{Bc:1,a:1});var gb;function hb(){gb||(gb=new fb);return gb}function kb(){}kb.prototype=new t;kb.prototype.constructor=kb;
kb.prototype.$classData=x({Kc:0},"scala.collection.mutable.MutationTracker$",{Kc:1,a:1});var lb;function mb(){this.Za=null;nb=this;ob||(ob=new A);ob||(ob=new A);pb||(pb=new qb);rb||(rb=new sb);C();tb();this.Za=D();ub();vb()}mb.prototype=new t;mb.prototype.constructor=mb;mb.prototype.$classData=x({Yb:0},"scala.package$",{Yb:1,a:1});var nb;function wb(){}wb.prototype=new t;wb.prototype.constructor=wb;
function E(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var c=Ya();b=ab(c,a);c=c.da;Ya();a=(0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0))===a?b^c:Pa(Qa(),a)}return a}return b instanceof n?(a=null===b?ba:b,b=new n(a.K,a.J),a=b.K,b=b.J,b===a>>31?a:a^b):ua(b)}wb.prototype.$classData=x({Uc:0},"scala.runtime.Statics$",{Uc:1,a:1});var xb;function F(){xb||(xb=new wb);return xb}
function yb(){}yb.prototype=new t;yb.prototype.constructor=yb;function zb(){}zb.prototype=yb.prototype;function G(a,b){a=Ab(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Ab(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function H(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function Bb(a){0===(32&a.ha)<<24>>24&&0===(32&a.ha)<<24>>24&&(a.Ta=new Ea(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.ha=(32|a.ha)<<24>>24);return a.Ta}function Cb(){this.Ta=null;this.ha=0}Cb.prototype=new t;Cb.prototype.constructor=Cb;
Cb.prototype.$classData=x({Cb:0},"java.lang.Character$",{Cb:1,a:1,b:1});var Db;function Eb(a){throw new Fb('For input string: "'+a+'"');}function Gb(){}Gb.prototype=new t;Gb.prototype.constructor=Gb;Gb.prototype.$classData=x({Jb:0},"java.lang.Integer$",{Jb:1,a:1,b:1});var Hb;function I(a,b){a.Wa=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace?Error():Error.captureStackTrace(a))}
class Ib extends Error{constructor(){super();this.Wa=null}Aa(){return this.Wa}i(){var a=ta(this),b=this.Aa();return null===b?a:a+": "+b}u(){return r.prototype.u.call(this)}get message(){var a=this.Aa();return null===a?"":a}get name(){return ta(this)}toString(){return this.i()}}function Jb(){}Jb.prototype=new t;Jb.prototype.constructor=Jb;function Kb(){}Kb.prototype=Jb.prototype;Jb.prototype.i=function(){return"\x3cfunction0\x3e"};function J(a){this.Ma=a}J.prototype=new t;J.prototype.constructor=J;
J.prototype.i=function(){return""+this.Ma};J.prototype.$classData=x({Sc:0},"scala.runtime.IntRef",{Sc:1,a:1,b:1});function K(a){this.Na=a}K.prototype=new t;K.prototype.constructor=K;K.prototype.i=function(){return""+this.Na};K.prototype.$classData=x({Tc:0},"scala.runtime.ObjectRef",{Tc:1,a:1,b:1});
function Lb(){this.$a=this.oa=0;Mb=this;this.oa=q("Seq");this.$a=q("Map");q("Set");nb||(nb=new mb);for(var a=this.$a,b=0,c=0,d=0,f=1,h=nb.Za.k();h.h();){var g=h.g();g=E(F(),g);b=b+g|0;c^=g;f=Math.imul(f,1|g);d=1+d|0}a=G(a,b);a=G(a,c);a=Ab(a,f);H(a^d)}Lb.prototype=new zb;Lb.prototype.constructor=Lb;Lb.prototype.$classData=x({Zb:0},"scala.util.hashing.MurmurHash3$",{Zb:1,ad:1,a:1});var Mb;function Nb(){this.Oa=null;Ob=this;var a=Ya(),b=+(new Date).getTime();ab(a,b);this.Oa=new Pb;new Ma}
Nb.prototype=new t;Nb.prototype.constructor=Nb;Nb.prototype.$classData=x({ub:0},"dotty.tools.scaladoc.Main$",{ub:1,a:1,Zc:1,Yc:1});var Ob;class Qb extends Ib{}function Rb(){}Rb.prototype=new t;Rb.prototype.constructor=Rb;function Sb(){}Sb.prototype=Rb.prototype;function Tb(a,b){if(0>b)return 1;var c=a.E();if(0<=c)return c===b?0:c<b?-1:1;c=0;for(a=a.k();a.h();){if(c===b)return 1;a.g();c=1+c|0}return c-b|0}function Ub(){this.z=null;Vb=this;this.z=new L}Ub.prototype=new t;Ub.prototype.constructor=Ub;
Ub.prototype.$classData=x({ec:0},"scala.collection.Iterator$",{ec:1,a:1,y:1,b:1});var Vb;function C(){Vb||(Vb=new Ub);return Vb}function M(){}M.prototype=new t;M.prototype.constructor=M;M.prototype.C=function(){throw new Wb("head of empty lazy list");};function N(){throw new Xb("tail of empty lazy list");}M.prototype.$classData=x({qc:0},"scala.collection.immutable.LazyList$State$Empty$",{qc:1,a:1,ld:1,b:1});var Yb;function Zb(){Yb||(Yb=new M);return Yb}function O(a){this.xa=a}O.prototype=new Kb;
O.prototype.constructor=O;O.prototype.$classData=x({Rc:0},"scala.scalajs.runtime.AnonFunction0",{Rc:1,ud:1,a:1,Vc:1});var pa=x({zb:0},"java.lang.Boolean",{zb:1,a:1,b:1,q:1,s:1},a=>"boolean"===typeof a),sa=x({Bb:0},"java.lang.Character",{Bb:1,a:1,b:1,q:1,s:1},a=>a instanceof k);class P extends Qb{}P.prototype.$classData=x({r:0},"java.lang.RuntimeException",{r:1,w:1,x:1,a:1,b:1});function $b(a){a.e="";return a}function Q(){this.e=null}Q.prototype=new t;Q.prototype.constructor=Q;Q.prototype.i=function(){return this.e};
Q.prototype.f=function(){return this.e.length};Q.prototype.$classData=x({Ob:0},"java.lang.StringBuilder",{Ob:1,a:1,Sa:1,Wc:1,b:1});function R(){}R.prototype=new t;R.prototype.constructor=R;function ac(){}ac.prototype=R.prototype;R.prototype.k=function(){return this};R.prototype.d=function(){return!this.h()};R.prototype.i=function(){return"\x3citerator\x3e"};R.prototype.ea=function(a,b,c,d){return cb(this,a,b,c,d)};function A(){bc||(bc=new cc)}A.prototype=new Sb;A.prototype.constructor=A;
A.prototype.$classData=x({cc:0},"scala.collection.Iterable$",{cc:1,dc:1,a:1,y:1,b:1});var ob;function dc(){}dc.prototype=new t;dc.prototype.constructor=dc;function ec(){}ec.prototype=dc.prototype;function cc(){tb()}cc.prototype=new Sb;cc.prototype.constructor=cc;cc.prototype.$classData=x({mc:0},"scala.collection.immutable.Iterable$",{mc:1,dc:1,a:1,y:1,b:1});var bc;function fc(){this.hb=null;gc=this;this.hb=hc(new S(new O(()=>Zb())))}fc.prototype=new t;fc.prototype.constructor=fc;
function ic(a,b,c){var d=new K(b),f=new J(c);return new S(new O(()=>{for(var h=d.Na,g=f.Ma;0<g&&!h.d();)h=N(U(h)),d.Na=h,g=-1+g|0,f.Ma=g;return U(h)}))}fc.prototype.$classData=x({oc:0},"scala.collection.immutable.LazyList$",{oc:1,a:1,sa:1,y:1,b:1});var gc;function ub(){gc||(gc=new fc);return gc}var ja=x({Ab:0},"java.lang.Byte",{Ab:1,Q:1,a:1,b:1,q:1,s:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);class jc extends P{}class kc extends P{constructor(a){super();I(this,a)}}
kc.prototype.$classData=x({Hb:0},"java.lang.IndexOutOfBoundsException",{Hb:1,r:1,w:1,x:1,a:1,b:1});x({Lb:0},"java.lang.NullPointerException",{Lb:1,r:1,w:1,x:1,a:1,b:1});var ka=x({Nb:0},"java.lang.Short",{Nb:1,Q:1,a:1,b:1,q:1,s:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);class Xb extends P{constructor(a){super();I(this,a)}}Xb.prototype.$classData=x({Qb:0},"java.lang.UnsupportedOperationException",{Qb:1,r:1,w:1,x:1,a:1,b:1});
class lc extends P{constructor(){super();I(this,"mutation occurred during iteration")}}lc.prototype.$classData=x({Ub:0},"java.util.ConcurrentModificationException",{Ub:1,r:1,w:1,x:1,a:1,b:1});class Wb extends P{constructor(a){super();I(this,a)}}Wb.prototype.$classData=x({Vb:0},"java.util.NoSuchElementException",{Vb:1,r:1,w:1,x:1,a:1,b:1});
class mc extends P{constructor(a){super();this.Ya=null;this.Ca=!1;this.ma=a;I(this,null)}Aa(){if(!this.Ca&&!this.Ca){if(null===this.ma)var a="null";else try{var b=this.ma;a=(void 0===b?"undefined":b.toString())+" (of class "+fa(this.ma).D.name+")"}catch(c){a="an instance of class "+fa(this.ma).D.name}this.Ya=a;this.Ca=!0}return this.Ya}}mc.prototype.$classData=x({Xb:0},"scala.MatchError",{Xb:1,r:1,w:1,x:1,a:1,b:1});function L(){}L.prototype=new ac;L.prototype.constructor=L;L.prototype.h=function(){return!1};
L.prototype.g=function(){throw new Wb("next on empty iterator");};L.prototype.$classData=x({fc:0},"scala.collection.Iterator$$anon$19",{fc:1,Da:1,a:1,qa:1,l:1,m:1});function nc(a,b){if(0>b)throw new kc(""+b);a=a.Qa(b);if(a.d())throw new kc(""+b);return a.Ra()}function sb(){vb()}sb.prototype=new ec;sb.prototype.constructor=sb;sb.prototype.$classData=x({lc:0},"scala.collection.immutable.IndexedSeq$",{lc:1,ic:1,a:1,sa:1,y:1,b:1});var rb;function V(a){this.Ga=a}V.prototype=new ac;
V.prototype.constructor=V;V.prototype.h=function(){return!this.Ga.d()};V.prototype.g=function(){if(this.Ga.d())return C().z.g();U(this.Ga).C()};V.prototype.$classData=x({pc:0},"scala.collection.immutable.LazyList$LazyIterator",{pc:1,Da:1,a:1,qa:1,l:1,m:1});function oc(){pc=this;D();D()}oc.prototype=new t;oc.prototype.constructor=oc;oc.prototype.$classData=x({tc:0},"scala.collection.immutable.List$",{tc:1,a:1,jc:1,sa:1,y:1,b:1});var pc;function tb(){pc||(pc=new oc)}
function qc(a,b,c){this.kb=this.ua=this.$=this.Z=this.Y=null;this.va=b;this.vc=c;this.G=a.I;this.Ja=this.G.c.length;this.Ka=this.n=0;this.A=this.va;this.ba=0;this.H=1;this.La=0;this.aa=this.Ja}qc.prototype=new t;qc.prototype.constructor=qc;e=qc.prototype;e.k=function(){return this};e.d=function(){return this.A<=this.n};e.i=function(){return"\x3citerator\x3e"};e.ea=function(a,b,c,d){return cb(this,a,b,c,d)};e.h=function(){return this.A>this.n};
e.g=function(){if(this.n===this.Ja){var a=(this.n-this.A|0)+this.va|0;if(a===this.aa){this.A<=this.n&&C().z.g();this.ba=1+this.ba|0;for(var b=null;0===b.c.length;)this.ba=1+this.ba|0,b=null;this.La=this.aa;var c=this.vc/2|0,d=this.ba-c|0;c=this.H=(1+c|0)-(0>d?-d|0:d)|0;switch(c){case 1:this.G=b;break;case 2:this.Y=b;break;case 3:this.Z=b;break;case 4:this.$=b;break;case 5:this.ua=b;break;case 6:this.kb=b;break;default:throw new mc(c);}this.aa=this.La+Math.imul(b.c.length,1<<Math.imul(5,-1+this.H|
0))|0;this.aa>this.va&&(this.aa=this.va);1<this.H&&(this.Ka=-1+(1<<Math.imul(5,this.H))|0)}1<this.H&&(a=a-this.La|0,b=this.Ka^a,1024>b?this.G=this.Y.c[31&(a>>>5|0)]:(32768>b?this.Y=this.Z.c[31&(a>>>10|0)]:(1048576>b?this.Z=this.$.c[31&(a>>>15|0)]:(33554432>b?this.$=this.ua.c[31&(a>>>20|0)]:(this.ua=this.kb.c[a>>>25|0],this.$=this.ua.c[0]),this.Z=this.$.c[0]),this.Y=this.Z.c[0]),this.G=this.Y.c[0]),this.Ka=a);this.A=this.A-this.n|0;a=this.G.c.length;b=this.A;this.Ja=a<b?a:b;this.n=0}a=this.G.c[this.n];
this.n=1+this.n|0;return a};e.$classData=x({uc:0},"scala.collection.immutable.NewVectorIterator",{uc:1,a:1,qa:1,l:1,m:1,ia:1});function qb(){tb()}qb.prototype=new ec;qb.prototype.constructor=qb;qb.prototype.$classData=x({xc:0},"scala.collection.immutable.Seq$",{xc:1,ic:1,a:1,sa:1,y:1,b:1});var pb;
function rc(){this.nb=null;wc=this;try{eb||(eb=new db);var a=Ta;Sa||(Sa=new Ra);var b=a(Sa,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");Hb||(Hb=new Gb);var c=null===b?0:b.length;0===c&&Eb(b);var d=b.charCodeAt(0),f=45===d;a=f?2147483648:2147483647;d=f||43===d?1:0;d>=b.length&&Eb(b);for(f=0;d!==c;){Db||(Db=new Cb);var h=Db,g=b.charCodeAt(d);if(256>g)var m=48<=g&&57>=g?-48+g|0:65<=g&&90>=g?-55+g|0:97<=g&&122>=g?-87+g|0:-1;else if(65313<=g&&65338>=g)m=-65303+g|0;else if(65345<=
g&&65370>=g)m=-65335+g|0;else{Xa||(Xa=new Wa);b:for(var p=Bb(h),B=0,T=p.c.length;;){if(B===T){var ib=-1-B|0;break b}var jb=(B+T|0)>>>1|0,sc=p.c[jb],tc=g===sc?0:g<sc?-1:1;if(0>tc)T=jb;else{if(0===tc){ib=jb;break b}B=1+jb|0}}B=0>ib?-2-ib|0:ib;if(0>B)m=-1;else{var uc=g-Bb(h).c[B]|0;m=9<uc?-1:uc}}var vc=10>m?m:-1;f=10*f+vc;(-1===vc||f>a)&&Eb(b);d=1+d|0}}catch(cd){throw cd;}this.nb=new qc(xc(),0,0)}rc.prototype=new t;rc.prototype.constructor=rc;
rc.prototype.$classData=x({zc:0},"scala.collection.immutable.Vector$",{zc:1,a:1,jc:1,sa:1,y:1,b:1});var wc;function vb(){wc||(wc=new rc);return wc}function W(a,b){this.qb=0;this.rb=a;this.Mc=b;this.qb=(0,b.xa)()|0}W.prototype=new ac;W.prototype.constructor=W;W.prototype.h=function(){lb||(lb=new kb);var a=this.qb;if(((0,this.Mc.xa)()|0)!==a)throw new lc;return this.rb.h()};W.prototype.g=function(){return this.rb.g()};
W.prototype.$classData=x({Lc:0},"scala.collection.mutable.MutationTracker$CheckedIterator",{Lc:1,Da:1,a:1,qa:1,l:1,m:1});function va(a){return Pa(Qa(),a)}var oa=x({Eb:0},"java.lang.Double",{Eb:1,Q:1,a:1,b:1,q:1,s:1,ka:1},a=>"number"===typeof a),na=x({Fb:0},"java.lang.Float",{Fb:1,Q:1,a:1,b:1,q:1,s:1,ka:1},a=>ma(a)),la=x({Ib:0},"java.lang.Integer",{Ib:1,Q:1,a:1,b:1,q:1,s:1,ka:1},a=>ia(a)),ra=x({Kb:0},"java.lang.Long",{Kb:1,Q:1,a:1,b:1,q:1,s:1,ka:1},a=>a instanceof n);
class Fb extends jc{constructor(a){super();I(this,a)}}Fb.prototype.$classData=x({Mb:0},"java.lang.NumberFormatException",{Mb:1,Xc:1,r:1,w:1,x:1,a:1,b:1});function q(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}var ha=x({xb:0},"java.lang.String",{xb:1,a:1,b:1,q:1,Sa:1,s:1,ka:1},a=>"string"===typeof a);function yc(){}yc.prototype=new t;yc.prototype.constructor=yc;function zc(){}zc.prototype=yc.prototype;yc.prototype.fa=function(){return this.B()};
yc.prototype.ea=function(a,b,c,d){return cb(this,a,b,c,d)};function X(a){this.S=0;this.bc=a;this.Ea=0;this.S=a.f()}X.prototype=new ac;X.prototype.constructor=X;X.prototype.h=function(){return 0<this.S};X.prototype.g=function(){if(0<this.S){var a=this.bc.j(this.Ea);this.Ea=1+this.Ea|0;this.S=-1+this.S|0;return a}return C().z.g()};X.prototype.$classData=x({ac:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{ac:1,Da:1,a:1,qa:1,l:1,m:1,b:1});function Ac(){}Ac.prototype=new zc;
Ac.prototype.constructor=Ac;function Bc(){}Bc.prototype=Ac.prototype;Ac.prototype.i=function(){return this.B()+"(\x3cnot computed\x3e)"};function Y(){}Y.prototype=new zc;Y.prototype.constructor=Y;function Cc(){}Cc.prototype=Y.prototype;
Y.prototype.u=function(){Mb||(Mb=new Lb);var a=Mb;if(this&&this.$classData&&this.$classData.p.ab)a:{var b=a.oa;a=this.f();switch(a){case 0:a=H(b^0);break a;case 1:a=b;b=this.j(0);a=H(G(a,E(F(),b))^1);break a;default:var c=this.j(0),d=E(F(),c);c=b=G(b,d);var f=this.j(1);f=E(F(),f);var h=f-d|0;for(d=2;d<a;){b=G(b,f);var g=this.j(d);g=E(F(),g);if(h!==(g-f|0)){b=G(b,g);for(d=1+d|0;d<a;)c=this.j(d),b=G(b,E(F(),c)),d=1+d|0;a=H(b^a);break a}f=g;d=1+d|0}a=H(G(G(c,h),f))}}else if(this instanceof Dc){for(a=
a.oa;!this.d();)this.C();a=H(a^0)}else a:if(b=a.oa,a=this.k(),a.h())if(c=a.g(),a.h()){d=a.g();h=E(F(),c);c=b=G(b,h);f=E(F(),d);h=f-h|0;for(d=2;a.h();){b=G(b,f);g=a.g();g=E(F(),g);if(h!==(g-f|0)){b=G(b,g);for(d=1+d|0;a.h();)c=a.g(),b=G(b,E(F(),c)),d=1+d|0;a=H(b^d);break a}f=g;d=1+d|0}a=H(G(G(c,h),f))}else a=H(G(b,E(F(),c))^1);else a=H(b^0);return a};Y.prototype.i=function(){var a=this.fa()+"(";if(this.d())a=""+a+")";else{var b=this.ea,c=new Ec;c.o=$b(new Q);a=b.call(this,c,a,", ",")").o.e}return a};
Y.prototype.F=function(a){return Tb(this,a)};Y.prototype.d=function(){return 0===this.F(0)};function Fc(){}Fc.prototype=new Bc;Fc.prototype.constructor=Fc;function Gc(){}Gc.prototype=Fc.prototype;function Z(){this.ta=null}Z.prototype=new Gc;Z.prototype.constructor=Z;function Hc(){}Hc.prototype=Z.prototype;Z.prototype.j=function(a){return this.ta.j(a)};Z.prototype.f=function(){return this.ta.f()};Z.prototype.d=function(){return this.ta.d()};function Ic(a){this.ta=a}Ic.prototype=new Hc;
Ic.prototype.constructor=Ic;e=Ic.prototype;e.k=function(){return new X(this)};e.B=function(){return"IndexedSeqView"};e.F=function(a){var b=this.f();return b===a?0:b<a?-1:1};e.E=function(){return this.f()};e.$classData=x({$b:0},"scala.collection.IndexedSeqView$Id",{$b:1,fd:1,bd:1,cd:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,hd:1,b:1,ed:1,W:1,dd:1,bb:1});function Jc(){}Jc.prototype=new Cc;Jc.prototype.constructor=Jc;function Kc(){}Kc.prototype=Jc.prototype;function Lc(){}Lc.prototype=new Cc;
Lc.prototype.constructor=Lc;function Mc(){}Mc.prototype=Lc.prototype;function Nc(a,b,c,d){b.e=""+b.e+c;a.X?a.d()||U(a).C():b.e+="\x3cnot computed\x3e";b.e=""+b.e+d;return b}function S(a){this.jb=null;this.Ha=!1;this.ib=a;this.Ia=this.X=!1}S.prototype=new Kc;S.prototype.constructor=S;e=S.prototype;e.B=function(){return"LinearSeq"};e.f=function(){for(var a=this,b=0;!a.d();)b=1+b|0,a=a.ya();return b};
e.F=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.d()?0:1;break a}if(b.d()){a=-1;break a}c=1+c|0;b=b.ya()}return a};e.j=function(a){return nc(this,a)};function U(a){if(!a.Ha&&!a.Ha){if(a.Ia)throw a=new P,I(a,"self-referential LazyList or a derivation thereof has no more elements"),a;a.Ia=!0;try{var b=(0,a.ib.xa)()}finally{a.Ia=!1}a.X=!0;a.ib=null;a.jb=b;a.Ha=!0}return a.jb}e.d=function(){return U(this)===Zb()};e.E=function(){return this.X&&this.d()?0:-1};e.Ra=function(){U(this).C()};
function hc(a){var b=a,c=a;for(b.d()||(b=N(U(b)));c!==b&&!b.d();){b=N(U(b));if(b.d())break;b=N(U(b));if(b===c)break;c=N(U(c))}return a}e.k=function(){return this.X&&this.d()?C().z:new V(this)};e.fa=function(){return"LazyList"};e.ea=function(a,b,c,d){hc(this);Nc(this,a.o,b,d);return a};e.i=function(){var a=new Q;$b(a);a.e="LazyList";return Nc(this,a,"(",")").e};e.Qa=function(a){return 0>=a?this:this.X&&this.d()?ub().hb:ic(ub(),this,a)};e.ya=function(){return N(U(this))};
e.$classData=x({nc:0},"scala.collection.immutable.LazyList",{nc:1,fb:1,pa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,ra:1,na:1,ca:1,W:1,la:1,lb:1,gb:1,mb:1,rc:1,gc:1,hc:1,sc:1,b:1});function Oc(){}Oc.prototype=new Mc;Oc.prototype.constructor=Oc;function Pc(){}Pc.prototype=Oc.prototype;function Qc(){this.I=null}Qc.prototype=new Kc;Qc.prototype.constructor=Qc;function Rc(){}e=Rc.prototype=Qc.prototype;e.B=function(){return"IndexedSeq"};e.F=function(a){var b=this.f();return b===a?0:b<a?-1:1};e.E=function(){return this.f()};
e.f=function(){return this instanceof Sc?this.Fa:this.I.c.length};e.k=function(){return xc()===this?vb().nb:new qc(this,this.f(),0)};e.fa=function(){return"Vector"};function Dc(){}Dc.prototype=new Kc;Dc.prototype.constructor=Dc;function Tc(){}e=Tc.prototype=Dc.prototype;e.B=function(){return"LinearSeq"};e.j=function(a){return nc(this,a)};e.d=function(){return this===D()};e.f=function(){for(var a=0;!this.d();)a=1+a|0,Uc();return a};
e.F=function(a){if(0>a)a=1;else a:for(;;){if(0===a){a=this.d()?0:1;break a}if(this.d()){a=-1;break a}Uc()}return a};e.fa=function(){return"List"};e.Qa=function(a){a:for(var b=this;;){if(0>=a||b.d())break a;a=-1+a|0;b=b.ya()}return b};function Vc(){this.I=null}Vc.prototype=new Rc;Vc.prototype.constructor=Vc;function Wc(){}Wc.prototype=Vc.prototype;function Sc(){this.I=null;this.Fa=0}Sc.prototype=new Wc;Sc.prototype.constructor=Sc;function Xc(){}Xc.prototype=Sc.prototype;
function Yc(){Zc=this;D();D()}Yc.prototype=new Tc;Yc.prototype.constructor=Yc;e=Yc.prototype;e.C=function(){throw new Wb("head of empty list");};function Uc(){throw new Xb("tail of empty list");}e.E=function(){return 0};e.k=function(){return C().z};e.ya=function(){Uc()};e.Ra=function(){this.C()};e.$classData=x({wc:0},"scala.collection.immutable.Nil$",{wc:1,md:1,fb:1,pa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,ra:1,na:1,ca:1,W:1,la:1,lb:1,gb:1,mb:1,rc:1,gc:1,hc:1,sc:1,gd:1,db:1,cb:1,yc:1,eb:1,b:1,$c:1});var Zc;
function D(){Zc||(Zc=new Yc);return Zc}function $c(){this.I=null;this.Fa=0;var a=hb().ob;hb();this.Fa=0;this.I=a}$c.prototype=new Xc;$c.prototype.constructor=$c;$c.prototype.j=function(a){throw new kc(a+" is out of bounds (empty vector)");};$c.prototype.$classData=x({Ac:0},"scala.collection.immutable.Vector0$",{Ac:1,id:1,od:1,nd:1,fb:1,pa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,ra:1,na:1,ca:1,W:1,la:1,lb:1,gb:1,mb:1,jd:1,ab:1,bb:1,kd:1,yc:1,db:1,cb:1,eb:1,b:1});var ad;
function xc(){ad||(ad=new $c);return ad}function Ec(){this.o=null}Ec.prototype=new Mc;Ec.prototype.constructor=Ec;e=Ec.prototype;e.B=function(){return"IndexedSeq"};e.k=function(){var a=new Ic(this);return new X(a)};e.F=function(a){var b=this.o.f();return b===a?0:b<a?-1:1};e.f=function(){return this.o.f()};e.E=function(){return this.o.f()};e.i=function(){return this.o.e};e.d=function(){return 0===this.o.f()};e.j=function(a){return new k(this.o.e.charCodeAt(a))};
e.$classData=x({Qc:0},"scala.collection.mutable.StringBuilder",{Qc:1,Cc:1,pa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,ra:1,na:1,ca:1,W:1,la:1,Oc:1,Hc:1,Pc:1,Fc:1,ia:1,Nc:1,Dc:1,Gc:1,Ec:1,rd:1,ab:1,bb:1,sd:1,Sa:1,b:1});function Pb(){this.pb=null;this.Jc=this.wa=0;this.pb=D();this.wa=0}Pb.prototype=new Pc;Pb.prototype.constructor=Pb;e=Pb.prototype;e.k=function(){return new W(C().z,new O(()=>this.Jc))};e.j=function(a){return nc(this.pb,a)};e.f=function(){return this.wa};e.E=function(){return this.wa};
e.d=function(){return 0===this.wa};e.B=function(){return"ListBuffer"};e.$classData=x({Ic:0},"scala.collection.mutable.ListBuffer",{Ic:1,pd:1,Cc:1,pa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,ra:1,na:1,ca:1,W:1,la:1,Oc:1,Hc:1,Pc:1,Fc:1,ia:1,qd:1,Gc:1,Ec:1,td:1,db:1,cb:1,Nc:1,Dc:1,eb:1,b:1});ba=new n(0,0);La.sb=ba;new (Ka(ha).ga)([]);Ob||(Ob=new Nb);for(var bd=Ob.Oa.k();bd.h();)(0,bd.g().xa)();
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
