name: Build and Test Scala-CLI Example

runs:
  using: composite
  steps:
    - name: Install CIRCT
      uses: ./.github/workflows/install-circt
    - name: Cache Scala-CLI
      uses: coursier/cache-action@v6
    - name: Setup Scala-CLI
      uses: VirtusLab/scala-cli-setup@v1
      with:
        jvm: adoptium:17
        apps: sbt
    - name: Generate Scala CLI Example
      shell: bash
      run: |
        # Determine the version and insert it into the example
        sbt emitVersion
        VERSION=$(cat version.txt)
        sed "s/@VERSION@/$VERSION/g" .github/workflows/build-scala-cli-example/chisel-example.scala > chisel-example.scala
        # If the version does NOT contain SNAPSHOT, remove line including snapshots repo
        if ! grep -qi 'snapshot' <<< $VERSION; then
          sed -i '1d' chisel-example.scala
        fi
    # Need to publishLocal to test the example
    - name: Publish Local
      shell: bash
      run: sbt "unipublish / publishLocal"
    - name: Test Scala CLI Example
      shell: bash
      run: scala-cli chisel-example.scala
