name: 'CD (firtool)'

on:
  workflow_dispatch:
  # Run every 15 minutes.
  schedule:
    - cron: '*/15 * * * *'

jobs:
  cd-circt:
    name: 'Check Version, Create PR'
    runs-on: ubuntu-24.04
    steps:
      - name: 'circt/update-circt'
        uses: circt/update-circt@747595acaf8443b3f8eac6d97bd43c158504a7b5 # v1.1.2
        with:
          user: chiselbot
          email: chiselbot@users.noreply.github.com
          pr-labels: |
            Dependency Update
          pr-reviewers: |
            seldridge
            jackkoenig
          should-create-pr: '.github/scripts/check-maven-for-llvm-firtool-version.sh'
          github-token: ${{ secrets.CHISEL_BOT_TOKEN }}
